# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # I'm assuming this setup will use VirtualBox as it's provider

  $initial_setup = <<-SCRIPT
  sudo setenforce 0
  sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  sudo rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
  sudo yum --security update -y
  sudo yum install -y puppet-agent
  SCRIPT

  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "centos/7"
    nginx.vm.hostname = "nginx.devops.com"
    nginx.vm.network "private_network", ip: "10.127.0.10"
    nginx.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    nginx.vm.provision "shell", inline: $initial_setup
  end

  config.vm.define "php" do |php|
    php.vm.box = "centos/7"
    php.vm.hostname = "php.devops.com"
    php.vm.network "private_network", ip: "10.127.0.20"
    php.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    php.vm.provision "shell", inline: $initial_setup
  end

  config.vm.define "redis" do |redis|
    redis.vm.box = "centos/7"
    redis.vm.hostname = "redis.devops.com"
    redis.vm.network "private_network", ip: "10.127.0.30"
    redis.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
    redis.vm.provision "shell", inline: $initial_setup
  end



  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
