# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # I'm assuming this setup will use VirtualBox as it's provider

  $initial_setup = <<-SCRIPT
  sudo setenforce 0
  sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  sudo rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
  sudo yum --security update -y
  sudo yum install -y puppet-agent
  SCRIPT

  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "centos/7"
    nginx.vm.hostname = "nginx.devops.com"
    nginx.vm.network "private_network", ip: "10.127.0.10"
    nginx.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    nginx.vm.provision "shell", inline: $initial_setup
    nginx.vm.provision "shell", inline: "sudo puppet module install puppet-nginx --version 0.7.0"
    nginx.vm.provision "puppet" do |puppet|
      puppet.manifests_path = ["vm", "./puppet"]
      puppet.manifest_file = "nginx.pp"
    end
  end

  config.vm.define "php" do |php|
    php.vm.box = "centos/7"
    php.vm.hostname = "php.devops.com"
    php.vm.network "private_network", ip: "10.127.0.20"
    php.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    php.vm.provision "shell", inline: $initial_setup
    php.vm.provision "shell", inline: "sudo puppet module install puppet-php --version 4.0.0"
    php.vm.provision "puppet" do |puppet|
      puppet.manifests_path = ["vm", "./puppet"]
      puppet.manifest_file = "php.pp"
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.box = "centos/7"
    redis.vm.hostname = "redis.devops.com"
    redis.vm.network "private_network", ip: "10.127.0.30"
    redis.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
    redis.vm.provision "shell", inline: $initial_setup
    redis.vm.provision "shell", inline: "sudo puppet module install arioch-redis --version 3.1.0"
    redis.vm.provision "puppet" do |puppet|
      puppet.manifests_path = ["vm", "./puppet"]
      puppet.manifest_file = "redis.pp"
    end
  end

end
